name: CI
on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Run tests
        run: docker-compose run --rm chirpstack-gateway-bridge make test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Generate Tag
        run: |
          echo "MY_TAG=$(echo $GITHUB_SHA | cut -c1-12)" >> $GITHUB_ENV
      -
        name: Setup Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      -
        name: Build and push container

        run: |
              docker login registry.lab.sprybts.net --username "${{ secrets.SPRY_LAB_REGISTRY_USERNAME }}" --password "${{ secrets.SPRY_LAB_REGISTRY_PASSWORD }}"
              echo '----'
              docker ps -a
              docker images
              echo '----'
              update-binfmts --enable
              echo '----'
              docker buildx build --platform linux/arm/v6 -f Dockerfile-armv6 -t registry.lab.sprybts.net/himb-gateway:${{ env.MY_TAG }} --push .
